#!/usr/bin/env python3
#! -*- coding: utf-8 -*-
import os
import time

os.system("clear")
time.sleep(1)
os.system("python3 /data/data/com.termux/files/boot/bootanimation/page.py")
time.sleep(1)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page0.py")
time.sleep(0.5)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page.py")
time.sleep(0.5)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page0.py")
time.sleep(0.5)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page.py")
time.sleep(0.5)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page0.py")
time.sleep(1)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page1.py")
time.sleep(0.5)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page2.py")
time.sleep(0.5)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page3.py")
time.sleep(0.5)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page4.py")
time.sleep(0.5)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page5.py")
time.sleep(0.5)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page6.py")
time.sleep(0.5)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page7.py")
time.sleep(0.5)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page8.py")
time.sleep(0.5)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page9.py")
time.sleep(0.5)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page10.py")
time.sleep(0.5)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page11.py")
time.sleep(0.5)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page12.py")
time.sleep(1.5)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page13.py")
time.sleep(0.5)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page12.py")
time.sleep(0.25)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page13.py")
time.sleep(0.25)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page12.py")
time.sleep(0.25)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page13.py")
time.sleep(0.25)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page12.py")
time.sleep(0.25)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page13.py")
time.sleep(0.25)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page12.py")
time.sleep(0.25)
os.system("clear && python3 /data/data/com.termux/files/boot/bootanimation/page13.py")
time.sleep(1)
os.system("mpv /data/data/com.termux/files/boot/login.mp3 && clear && python3 /data/data/com.termux/files/chroot/chrootpy")
